# Setup
title:        Shivaling Sannalli's Blog
tagline:      Blog with flavours of tech and no techs
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Shivaling Sannalli
  url:        http://scsannalli.github.io 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
